preset: symfony

disabled:
  - phpdoc_scalar
  - no_blank_lines_between_imports
  - new_with_braces
  - phpdoc_separation
  - concat_without_spaces
  - phpdoc_annotation_without_dot
  - unalign_double_arrow
