language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

sudo: false

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --verbose
  - phpunit --coverage-clover=coverage.clover

after_script:
  - if [ $TRAVIS_PHP_VERSION != 7.* && $TRAVIS_PHP_VERSION != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION != 7.* && $TRAVIS_PHP_VERSION != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
