language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

matrix:
  include:
    - php: 5.3
      env: setup=lowest
    - php: 5.3
      env: setup=stable
    - php: 5.4
      env: setup=lowest
    - php: 5.4
      env: setup=stable
    - php: 5.5
      env: setup=lowest
    - php: 5.5
      env: setup=stable
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=stable
  allow_failures:
    - php: hhvm
  fast_finish: true
