language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

sudo: false

before_script:
  - composer install --dev

script: vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
